{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "wordle.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wordle.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.ingressRoute.routes }}
    - match: {{ .match }}
      kind: {{ default "Rule" .kind }}
      services:
        {{- if .services }}
        {{- toYaml .services | nindent 8 }}
        {{- else }}
        - kind: Service
          name: {{ $fullName }}
          port: {{ $svcPort }}
        {{- end }}
    {{- end }}
{{- end }}
