apiVersion: v1
kind: Service
metadata:
  name: {{ include "agduard-exporter.fullname" . }}
  labels:
    {{- include "agduard-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "agduard-exporter.selectorLabels" . | nindent 4 }}
