config: |
  @version: 3.35
  @include "scl.conf"
  source s_network_tcp {
    syslog(transport(tcp) port(601));
  };
  log {
  	source {
  		network();
  	};
  	destination { file("/var/log/${YEAR}-${MONTH}-syslog"); };
  };
