{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "donetick.minio.fullname" . }}
  namespace: {{ include "donetick.namespace" . }}
spec:
  clusterIP: None
  selector:
    {{- include "donetick.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: api
      targetPort: {{ .Values.minio.service.apiPort }}
      protocol: TCP
{{- end }}
