{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "donetick.minio.fullname" . }}-service
  namespace: {{ include "donetick.namespace" . }}
  labels:
    {{- include "donetick.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: api
      port: api
      targetPort: {{ .Values.minio.service.apiPort }}
      protocol: TCP
    - name: console
      port: console
      targetPort: {{ .Values.minio.service.consolePort }}
      protocol: TCP
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
{{- end }}
